#!/usr/bin/env bash

# Transfer a file using scp to a remote server


if [ $# -le 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	src_file="$1"
	user="$3"
	key="$4"
	host="$2"

	scp -o StrictHostKeyChecking=no -i "$key" "$src_file" "$user@$host":~/
fi

