#!/usr/bin/env bash
# Script to fix an nginx server listening on wrong port.
sudo sed -i 's/8080/80/' /etc/nginx/sites-enabled/default
sudo sed -i 's/ipv6only=on//' /etc/nginx/sites-enabled/default
sudo service nginx restart
