#!/usr/bin/env bash
# Process a file

echo $$ > /var/run/myscript.pid

delete_file() {
	rm /var/run/myscript.pid
	exit
}

trap 'delete_file' SIGTERM SIGQUIT

trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
