#!/usr/bin/env bash
# Process a file
PID_FILE="/var/run/myscript.pid"
echo $$ > "$PID_FILE"

delete_file() {
	rm "$PID_FILE"
	exit
}

trap 'delete_file' SIGQUIT

trap "echo 'I hate the kill command' && delete_file" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
