#!/usr/bin/env bash
# A tale of passwd

while IFS=':' read -r uname passwd uid g_id gecos hdir shell; do
	echo "The user $uname is part of the $g_id gang, lives in $hdir and rides $shell. $uid's place is protected by the passcode $passwd, more info about the user here: $gecos"
done < /etc/passwd
