#!/usr/bin/env bash
# Modifies the hosts file in a docker image
cp /etc/hosts ~/hosts.bak
echo "127.0.0.2          localhost" >> ~/hosts.bak
echo "8.8.8.8            facebook.com" >> ~/hosts.bak
cp ~/hosts.bak /etc/hosts
