#!/usr/bin/env bash
# Configure nginx to run as nginx ( basically running as non root)
sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chown nginx:nginx /var/log/nginx
pkill apache2
sudo -u nginx nginx -c /etc/nginx/nginx.conf
