#!/usr/bin/env bash
# Configure nginx to run as nginx ( basically running as non root )
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx nginx
